-- liquibase formatted sql

-- changeset oalekseenko:1
create table socks_pairs (
    id bigint generated by default as identity primary key,
    color varchar not null,
    cotton_part int not null,
    quantity int not null
)